### ISSUE TITLE
An error when calculate monthly anomalies because of cdo 

### ISSUE THREAD

**Issue by shen159876** [pmlmodelling/nctoolkit#16]
My data is from ERSST: V5( https://psl.noaa.gov/data/gridded/data.noaa.ersst.v5.html), contains global monthly SST.

I calculate monthly anomalies using the code:

```
file1 = '/mnt/e/science/hist-resIPO/data/ersst5.nc'

ds = nc.open_data(file1)

ds.monthly_anomaly(baseline=[1971, 2000])

```
And i got the bug like this:
`
ValueError: cdo(1) monmean: Process startedcdo(2) ymonmean: Process startedcdo(3) selyear: Process startedcdo    ymonsub (Abort): Fields have different size (vfarsub)terminate called recursivelyterminate called without an active exceptionterminate called recursivelyAborted (core dumped)`

My cdo version is 1.9.8.

**Comment by r4ecology** [comment]
Thanks for the bug report @shen159876 .

This seems to be a bug within that version of CDO. I have run your code with CDO version 1.9.10 and that is fine.

It is caused by a bug mentioned here [here](https://code.mpimet.mpg.de/projects/cdo/news): "Ymonarith: failed with variables on different grids". In your case "time_bnds" and "sst" have different grids so CDO is failing. You can get around this with the code below:

    ds = nc.open_data("sst.mnmean.nc")
    ds.select(variables = "sst")
    ds.monthly_anomaly(baseline=[1971, 2000])
    ds.run()

I'll see how to modify the method. The best I can probably do for this, code wise, is to check whether variables have different grids when CDO<1.9.10 and then throw an error if there are. In theory, nctoolkit could make an educated guess which variables are wanted, but that is guaranteed to start dropping variables people want.

I'll leave this open and try to code something up early next week.

**Comment by r4ecology** [comment]
I've just made a commit that largely resolves the issue: https://github.com/pmlmodelling/nctoolkit/commit/45191ce01fd1a48a8ca699f3bb92508f48263945. 

nctoolkit will now throw an error "Variables have different grids. This causes problems with the CDO version installed. Select specific variables before monthly_anomaly or upgrade to CDO>=1.9.10. See npoints in dataset contents to identify differen    ces in grids" for cases like this.

I will leave the issue open for a while as there might be a smarter way to resolve the issue.

**Comment by shen159876** [comment]
> Thanks for the bug report @shen159876 .
> 
> This seems to be a bug within that version of CDO. I have run your code with CDO version 1.9.10 and that is fine.
> 
> It is caused by a bug mentioned here [here](https://code.mpimet.mpg.de/projects/cdo/news): "Ymonarith: failed with variables on different grids". In your case "time_bnds" and "sst" have different grids so CDO is failing. You can get around this with the code below:
> 
> ```
> ds = nc.open_data("sst.mnmean.nc")
> ds.select(variables = "sst")
> ds.monthly_anomaly(baseline=[1971, 2000])
> ds.run()
> ```
> 
> I'll see how to modify the method. The best I can probably do for this, code wise, is to check whether variables have different grids when CDO<1.9.10 and then throw an error if there are. In theory, nctoolkit could make an educated guess which variables are wanted, but that is guaranteed to start dropping variables people want.
> 
> I'll leave this open and try to code something up early next week.

Thanks @r4ecology ,
Hope nctoolkit will be smart in future 👍 , it is really useful in the field of climate changes, as the name meaning ,it is a good tool.
