### ISSUE TITLE
An alternative of ds.regrid() for exporting time series.

### ISSUE THREAD

**Issue by afgheysari** [pmlmodelling/nctoolkit#20]
The challenge:

The current process of exporting time series is to call `ds.regrid()` with 1-member lat/lon arrays pointing to the coordinates. It works fine for a one-time export. However, running regrid() would alter the original dataset so it is not possible to export time series at another coordinate without reopening the *.nc files and redefining ds. One alternative may be copying the database by ds.copy before running the regrid() but it would be troublesome when the dataset is large.

Defining a dedicated function for exporting time series in (read-only) would be very useful. Example: `ds.tsexport(lat = lat1, lon= lon1, method=bil)`

Thank you

**Comment by r4ecology** [comment]
Is copying the dataset a major problem in this case? If you run `ds.copy`, an actual on-disk copy will not be made.

So if I did the following:

    ds1 = ds.copy()
    ds2 = ds.copy()
    ds3 = ds.copy(0
    ds4 = ds.copy()

You would see the following

    ds1.current == ds2.current

    ds3.current == ds4.current

The way `copy` works is it generates a new dataset with the copied dataset as its starting point, with the `current` state of the dataset being the same. Behind the scenes, nctoolkit will automatically delete temporary files generated so it doesn't clog up your temporary folder.

So if I delete a dataset, the temporary file associated with it will be removed from disk. Test as follows

    ds.tmean()
    ds.run()
    import os
    x = ds[0]
    os.path.exists(x)
    del ds
    os.path.exists(x)

On the other hand, if I copy the dataset before deleting it, the `current` file will not be deleted:

    ds.tmean()
    ds.run()
    ds1 = ds.copy()
    import os
    x = ds[0]
    os.path.exists(x)
    del ds
    os.path.exists(x)

Let me know if that clarifies things. I will also improve the website section about `copy`.

**Comment by afgheysari** [comment]
What I meant was a function provided with lat/lon that could reach the nearest neighbour/neighbours on the grid and return the time series for a single location without the unnecessary regrid.

The `copy` does the job when the dataset is small. I see that the new copied dataset points to the same nc files, as the `current`  attribute indicates. But let's imagine an extreme case in which the nc files are very large, and you are running a code on a server that fetches and returns time series for single lat/lon coordinates upon request, and does it thousands of times.

Based on your elaboration:
1. Does it mean a dataset `copy ` is just a pointer to the nc files and doesn't consume storage/memory as much as the nc files?
2. What kind of temporary files are created (and removed) in each `copy` instance? It may not be disk friendly if a large dataset is copied and deleted when the dataset is copied numerous times. So even if the code doesn't clutter the temp folder, redundant disk operations are not a good idea when dealing with large datasets.

**Comment by r4ecology** [comment]
Does it mean a dataset copy is just a pointer to the nc files and doesn't consume storage/memory as much as the nc files?

The answer to that is yes. The `copy` method does not create or remove any temporary files. Roughly speaking, it works the way `deepcopy` works from the `copy` module in Python, and not the way the `copy` method works that does a shallow copy. `ds.copy()` will do nothing whatsoever to the temporary files. It simply modifies which datasets point to them and keeps track of this so that temporary files are removed when they are no longer needed.

    What kind of temporary files are created (and removed) in each copy instance? It may not be disk friendly if a large dataset is copied and deleted when the dataset is copied numerous times. So even if the code doesn't clutter the temp folder, redundant disk operations are not a good idea when dealing with large datasets.

The dataset will not be copied and deleted multiple times.  If I do the following, the temporary files will remain untouched.

    ds1 = ds.copy()
    ds2 = ds.cop()
    del ds1
    del ds2

Likewise, if I did this

    ds1 = ds.copy()
    ds.regrid("grid.nc")

that will generate a new `ds.current`, but the `ds1.current` will be untouched.


    What I meant was a function provided with lat/lon that could reach the nearest neighbour/neighbours on the grid and return the time series for a single location without the unnecessary regrid.

I am not quite sure what you mean. What do you mean by "without the unnecessary regrid"? By definition you have to regrid in this case? nctoolkit can use nearest neighbour in `regrid`.

**Comment by afgheysari** [comment]
Thanks for the detailed explanation. That sounds good.  So in this case a combination of `copy `and `regrid` will do the job.

`I am not quite sure what you mean. What do you mean by "without the unnecessary regrid"? By definition you have to regrid in this case? nctoolkit can use nearest neighbour in regrid.`

It depends on how we define regrid. We can regrid to a one-node grid but I was thinking maybe you could define a faster function for exporting time series without going through `copy ` and `regrid`.

**Comment by r4ecology** [comment]
I will leave the issue open for now. 

The only way I can think of solving the problem is allowing **kwargs in `to_nc`, `to_xarray` etc. That would let you export a subset of the data. So you could have `ds.to_dataframe(lon = 10, lat = 60])` and it would only give you the lon/lat you have supplied. Something similar could work for time, example `ds.to_dataframe(year = 2000)`.

**Comment by robertjwilson** [comment]
The latest releases of nctoolkit now let you call `subset` args when using the `to_` methods. This is the most useful way to address the issue.
