### ISSUE TITLE
import error"IndexError: list index out of range"

### ISSUE THREAD

**Issue by advernturer** [pmlmodelling/nctoolkit#42]
python 3.10 
cdo 2.03
```
IndexError                                Traceback (most recent call last)
Cell In[20], line 1
----> 1 import nctoolkit as nc

File ~/anaconda3/envs/sfcWind/lib/python3.10/site-packages/nctoolkit/__init__.py:54
     52 cdo_check = cdo_check.replace("b'", "").strip()
     53 cdo_version = cdo_check.split("(")[0].strip().split(" ")[-1]
---> 54 if valid(cdo_version) is False:
     55     print(
     56         "Please install CDO version 1.9.3 or above: https://code.mpimet.mpg.de/projects/cdo/ or https://anaconda.org/conda-forge/cdo"
     57     )

File ~/anaconda3/envs/sfcWind/lib/python3.10/site-packages/nctoolkit/__init__.py:26, in valid(string)
     24 wanted = ""
     25 n = 3
---> 26 where = [m.start() for m in re.finditer(sub, string)][n - 1]
     28 string = re.sub("[A-Za-z]", "", string)
     30 before = string[:where]

IndexError: list index out of range

```

**Comment by robertjwilson** [comment]
Which version of nctoolkit are you using? This looks like an oldish version, probably > 1 year old.

This error is probably due to changes they made in version 2.0.0 in CDO, which broke nctoolkit. These problems have been resolved months ago, but was fixed by a release in May 2022. 

You should be able to resolve this updating to nctoolkit version 0.8.6. However, you also should update CDO, as they have fixed a couple of bugs since that release.

**Comment by robertjwilson** [comment]
Did this resolve the issue @advernturer? If so, I will close the issue.

**Comment by advernturer** [comment]
yes



At 2023-01-10 16:58:20, "Robert Wilson" ***@***.***> wrote:

Did this resolve the issue @advernturer? If so, I will close the issue.
