### ISSUE TITLE
Garbled plot

### ISSUE THREAD

**Issue by platipodium** [pmlmodelling/nctoolkit#61]
Running the example 

```
import nctoolkit as nc
ds = nc.open_data("sst.mon.mean.nc")
ds.plot()
```

Creates a garbled plot on my machine (Mac M1 mamba/pip python11), problem in all browsers (Safari, Firefox, Chrome).  Y dimension not correct

<img width="1209" alt="garbled" src="https://github.com/pmlmodelling/nctoolkit/assets/2676409/bde6124c-7e20-472b-850c-98249287ed6c">

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by robertjwilson** [comment]
I am able to reproduce this problem @platipodium . It appears to be caused by an update to panel 14 days ago. Downgrading panel to 0.14.4 fixes the issue.

I'll pin the panel version on conda and do a quick release on pypi to pin it there. Meanwhile, I'll investigate whether the nctoolkit plotting code needs to change or whether it's something hvplot devs need to fix.

**Comment by robertjwilson** [comment]
This should now be fixed temporarily with a quick release I've just made to nctoolkit's plotting dependency ncplot: [here](https://github.com/pmlmodelling/ncplot/releases/tag/v0.3.3).

The cause of it was that hvplot's `image` method was not able to fit the browser window when you set `responsive=True`. I've fixed the problem by setting `responsive=False`. This means you can get a smallish plot window, but it's better than something compressed.

However, they appear to be on top of the issue at hvplot. I pointed it out to them and they said a code update was coming in the next day or so and a new release fixing the problem is incoming: [here](https://github.com/holoviz/hvplot/issues/1074#issuecomment-1573323252)

**Comment by platipodium** [comment]
Looking nice now! Thanks for the quick fix.
