### ISSUE TITLE
[JOSS] Clarify which libraries are used for core functionalities

### ISSUE THREAD

**Issue by malmans2** [pmlmodelling/nctoolkit#69]
The paper mentions that `nctoolkit` is built on top of CDO.
Therefore, I wouldn't expect to see that many libraries in the [requirement list](https://github.com/pmlmodelling/nctoolkit/blob/master/requirements.txt). 

I'll use `xarray` as example. Is it only used to return `xarray` objects?
If that's the case, I would make it optional and return an informative error if `to_xarray()` is used and `xarray` is not installed.

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by malmans2** [comment]
Got it. Because plotting is just one of many core functionalities, my suggestion is to keep the list of mandatory dependencies small.

It looks like you already isolated plotting in another package ([ncplot](https://github.com/pmlmodelling/ncplot)).

How about:
```
pip install nctoolkit  # minimal
pip install nctoolkit[plot]  # plotting packages as well
pip install nctoolkit[complete] # everything
```

With conda:
```
conda install -c conda-forge nctoolkit  # minimal
```
or 
```
conda install -c conda-forge nctoolkit ncplot  # plotting packages as well
```

**Comment by platipodium** [comment]
I support this separation of concerns.

**Comment by robertjwilson** [comment]
I agree the dependencies cause some issues, though mostly with conda installations due to version resolving issues.

I don't however see how plotting is an optional dependency. This is something that 99% of users will have to use, so I'm not sure that splitting it out will do anything but annoy people.

I've spoken with a few users of the package to get views, and they seemed clear that separating this out would annoy them. This is especially true for people who work with fresh conda environments all the time, and they don't want to have to remember how to install it.

There is a case perhaps for a nctoolkit-core package on conda (much like geoviews-core etc.), which would side-step conda installation problems and just be for pure post-processing, not plotting. But it's clear to me if the time spent creating and then maintaing this are worth it, as the appeal is likely very limited. 

Open to have my mind changed.

**Comment by robertjwilson** [comment]
The core dependencies are currently listed in the Acknowledgements section of the paper. I have just updated the paper so that it states which key libraries are required for plotting in the Acknowledgements section.
