### ISSUE TITLE
[JOSS] Add ds.bottom?

### ISSUE THREAD

**Issue by malmans2** [pmlmodelling/nctoolkit#73]
I was looking at the cheatsheet, and I noticed `ds.top()`.
I'd find `ds.bottom()` very useful as it's a diagnostic more complicated to get for ocean data because the index changes.

This is more of a feature request than a review comment.

https://github.com/openjournals/joss-reviews/issues/5494

**Comment by robertjwilson** [comment]
A `ds.bottom` method already exists: https://nctoolkit.readthedocs.io/en/latest/generated/nctoolkit.DataSet.bottom.html?highlight=bottom#nctoolkit.DataSet.bottom

That method will only extract the actual bottom level in the dataset.

For ocean data, there is a separate method for creating a mask which will identify the bottom cell in ocean data: https://nctoolkit.readthedocs.io/en/latest/generated/nctoolkit.DataSet.bottom_mask.html?highlight=bottom_mask

An extra arg should possibly be added to `bottom`, so that it can call when `bottom_mask` when you are dealing with oceanic data etc.

**Comment by malmans2** [comment]
Got it, thanks.
If your code (or CDO) don't look for that variable already, keep in mind that some NetCDF could have a variable that defines the bottom. The CF standard name is `model_level_number_at_sea_floor`

**Comment by robertjwilson** [comment]
Thanks. I'll put using that in `mask` onto my to-do list.
