### ISSUE TITLE
Cannot import nctoolkit after installation

### ISSUE THREAD

**Issue by Gilaverbuch** [pmlmodelling/nctoolkit#87]
Hi, 

I used conda0forge to download the latest nctoolkit version. When I try to import the package I get the following error:

`File ~/opt/miniconda3/envs/pysst/lib/python3.11/site-packages/nctoolkit/__init__.py:54
     52 cdo_check = cdo_check.replace("b'", "").strip()
     53 cdo_version = cdo_check.split("(")[0].strip().split(" ")[-1]
---> 54 if valid(cdo_version) is False:
     55     print(
     56         "Please install CDO version 1.9.3 or above: https://code.mpimet.mpg.de/projects/cdo/ or https://anaconda.org/conda-forge/cdo"
     57     )

File ~/opt/miniconda3/envs/pysst/lib/python3.11/site-packages/nctoolkit/__init__.py:26, in valid(string)
     24 wanted = ""
     25 n = 3
---> 26 where = [m.start() for m in re.finditer(sub, string)][n - 1]
     28 string = re.sub("[A-Za-z]", "", string)
     30 before = string[:where]

IndexError: list index out of range`

What I do not understand is that the CDO version is 2.2.0, so why do I get this error?

Thanks, 
Gil

**Comment by robertjwilson** [comment]
Hi @Gilaverbuch 

Can you confirm that you have the latest version installed?

This appears old. The init file only has 50 lines, and it hasn't been updated in 7 months: https://github.com/pmlmodelling/nctoolkit/blob/master/nctoolkit/__init__.py

My guess is that conda has installed a very old version of nctoolkit. This causes problems because CDO versions 2.0.x made changes that broke nctoolkit, so very old versions of nctoolkit only work with CDO versions below 2.0.

Try the following

    conda install nctoolkit=0.9.4

That should solve the problem.

**Comment by Gilaverbuch** [comment]
Hi, 

Thanks. Indeed it was an old version. For some reason installing the new version via `conda install` did not work, but using `pip install` worked.

**Comment by robertjwilson** [comment]
Thanks. Any further issues let me know. 

I recommend switching to mamba. Mambaforge is an easy way to install it. 
https://github.com/conda-forge/miniforge

Mamba will always install packages and update environments a lot faster than conda. And you won't running into freezing environment issues.
